# Generated by Django 5.0.1 on 2025-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_tuningmodels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tuningmodels",
            name="alpha",
            field=models.IntegerField(verbose_name="Alpha"),
        ),
        migrations.AlterField(
            model_name="tuningmodels",
            name="temperature",
            field=models.IntegerField(verbose_name="Temperature "),
        ),
    ]
